deployment:
  tasks:
    # Ensure environment
    - export NODE_ENV=production
    - export NEXT_TELEMETRY_DISABLED=1
    - export PATH=/opt/alt/alt-nodejs18/root/usr/bin:/usr/bin:$PATH
    - export NODE_OPTIONS=--max_old_space_size=1024
    - export NPM_CONFIG_FUND=false
    - export NPM_CONFIG_AUDIT=false

    # Clean deploy dir (keep tmp for Passenger)
    - cd $DEPLOYPATH && mkdir -p tmp
    - cd $DEPLOYPATH && rm -rf .next .next-standalone public server.js app.js || true

    # Install and build in repo workspace
    - npm ci --no-audit --no-fund --prefer-offline || npm install --no-audit --no-fund
    - npm run build

    # Publish artifacts to the deployment path (public_html)
    - mkdir -p $DEPLOYPATH/.next
    - cp -R .next/standalone $DEPLOYPATH/.next-standalone
    - cp -R .next/static $DEPLOYPATH/.next/static
    - cp -R public $DEPLOYPATH/public
    - cp server.js $DEPLOYPATH/server.js

    # Create the Node entrypoint (app.js launches Next standalone server)
    - bash -lc 'printf "process.env.PORT=process.env.PORT||\\\"3000\\\";require(\\\"./.next-standalone/server.js\\\");" > $DEPLOYPATH/app.js'

    # Ensure LiteSpeed/Passenger configuration (.htaccess) is present
    - bash -lc 'cat > $DEPLOYPATH/.htaccess <<EOF\nPassengerEnabled on\nPassengerNodejs /opt/alt/alt-nodejs18/root/usr/bin/node\nPassengerAppRoot $DEPLOYPATH\nPassengerStartupFile server.js\nPassengerAppEnv production\nPassengerBaseURI /\nEOF'

    # Restart Passenger
    - touch $DEPLOYPATH/tmp/restart.txt

