#!/bin/bash
# Copy and rename Zaika photos automatically

SOURCE="/Users/macbook/Downloads/ZAIKA PHOTOS"
TARGET="public"

echo "=== Copying Zaika Photos ==="
echo ""

# Copy files with proper renaming
cp "$SOURCE/Ajwaini Fish tikka.png" "$TARGET/ajwaini-fish-tikka.png" 2>/dev/null && echo "✅ ajwaini-fish-tikka.png" || echo "⚠️  Missing: Ajwaini Fish tikka.png"
cp "$SOURCE/Aloo Tikki.png" "$TARGET/aloo-tikki.png" 2>/dev/null && echo "✅ aloo-tikki.png" || echo "⚠️  Missing: Aloo Tikki.png"
cp "$SOURCE/Cheese stuffed naan.png" "$TARGET/cheese-stuffed-naan.png" 2>/dev/null && echo "✅ cheese-stuffed-naan.png" || echo "⚠️  Missing: Cheese stuffed naan.png"
cp "$SOURCE/Chicken Pad Pao.png" "$TARGET/chicken-pad-pao.png" 2>/dev/null && echo "✅ chicken-pad-pao.png" || echo "⚠️  Missing: Chicken Pad Pao.png"
cp "$SOURCE/Chicken dum biryani.png" "$TARGET/chicken-dum-biryani.png" 2>/dev/null && echo "✅ chicken-dum-biryani.png" || echo "⚠️  Missing: Chicken dum biryani.png"
cp "$SOURCE/Chicken tikka makhni.png" "$TARGET/chicken-tikka-makhni.png" 2>/dev/null && echo "✅ chicken-tikka-makhni.png" || echo "⚠️  Missing: Chicken tikka makhni.png"
cp "$SOURCE/Chicken tikka masala.png" "$TARGET/chicken-tikka-masala.png" 2>/dev/null && echo "✅ chicken-tikka-masala.png" || echo "⚠️  Missing: Chicken tikka masala.png"
cp "$SOURCE/Chicken tikka.png" "$TARGET/chicken-tikka.png" 2>/dev/null && echo "✅ chicken-tikka.png" || echo "⚠️  Missing: Chicken tikka.png"
cp "$SOURCE/Dal tadkha.png" "$TARGET/dal-tadkha.png" 2>/dev/null && echo "✅ dal-tadkha.png" || echo "⚠️  Missing: Dal tadkha.png"
cp "$SOURCE/Espresso martini.png" "$TARGET/espresso-martini.png" 2>/dev/null && echo "✅ espresso-martini.png" || echo "⚠️  Missing: Espresso martini.png"
cp "$SOURCE/Fennel collins.png" "$TARGET/fennel-collins.png" 2>/dev/null && echo "✅ fennel-collins.png" || echo "⚠️  Missing: Fennel collins.png"
cp "$SOURCE/Fish Amritsari.png" "$TARGET/fish-amritsari.png" 2>/dev/null && echo "✅ fish-amritsari.png" || echo "⚠️  Missing: Fish Amritsari.png"
cp "$SOURCE/Garlic butter naan.png" "$TARGET/garlic-butter-naan.png" 2>/dev/null && echo "✅ garlic-butter-naan.png" || echo "⚠️  Missing: Garlic butter naan.png"
cp "$SOURCE/Goan fish curry.png" "$TARGET/goan-fish-curry.png" 2>/dev/null && echo "✅ goan-fish-curry.png" || echo "⚠️  Missing: Goan fish curry.png"
cp "$SOURCE/Gulaab sour.png" "$TARGET/gulaab-sour.png" 2>/dev/null && echo "✅ gulaab-sour.png" || echo "⚠️  Missing: Gulaab sour.png"
cp "$SOURCE/Gulab jamum.png" "$TARGET/gulab-jamum.png" 2>/dev/null && echo "✅ gulab-jamum.png" || echo "⚠️  Missing: Gulab jamum.png"
cp "$SOURCE/Kadhai Paneer.png" "$TARGET/kadhai-paneer.png" 2>/dev/null && echo "✅ kadhai-paneer.png" || echo "⚠️  Missing: Kadhai Paneer.png"
cp "$SOURCE/Kahada palak gosht.png" "$TARGET/kahada-palak-gosht.png" 2>/dev/null && echo "✅ kahada-palak-gosht.png" || echo "⚠️  Missing: Kahada palak gosht.png"
cp "$SOURCE/Keema samosa.png" "$TARGET/keema-samosa.png" 2>/dev/null && echo "✅ keema-samosa.png" || echo "⚠️  Missing: Keema samosa.png"
cp "$SOURCE/Kulfi.png" "$TARGET/kulfi.png" 2>/dev/null && echo "✅ kulfi.png" || echo "⚠️  Missing: Kulfi.png"
cp "$SOURCE/Lamb rogan josh.png" "$TARGET/lamb-rogan-josh.png" 2>/dev/null && echo "✅ lamb-rogan-josh.png" || echo "⚠️  Missing: Lamb rogan josh.png"
cp "$SOURCE/Macchiato.png" "$TARGET/macchiato.png" 2>/dev/null && echo "✅ macchiato.png" || echo "⚠️  Missing: Macchiato.png"
cp "$SOURCE/Mango lassi.png" "$TARGET/mango-lassi.png" 2>/dev/null && echo "✅ mango-lassi.png" || echo "⚠️  Missing: Mango lassi.png"
cp "$SOURCE/Masala tea.png" "$TARGET/masala-tea.png" 2>/dev/null && echo "✅ masala-tea.png" || echo "⚠️  Missing: Masala tea.png"
cp "$SOURCE/Missi roti.png" "$TARGET/missi-roti.png" 2>/dev/null && echo "✅ missi-roti.png" || echo "⚠️  Missing: Missi roti.png"
cp "$SOURCE/Mixed Veg.png" "$TARGET/mixed-veg.png" 2>/dev/null && echo "✅ mixed-veg.png" || echo "⚠️  Missing: Mixed Veg.png"
cp "$SOURCE/Murgh Awadhi Korma.png" "$TARGET/murgh-awadhi-korma.png" 2>/dev/null && echo "✅ murgh-awadhi-korma.png" || echo "⚠️  Missing: Murgh Awadhi Korma.png"
cp "$SOURCE/Negroni.png" "$TARGET/negroni.png" 2>/dev/null && echo "✅ negroni.png" || echo "⚠️  Missing: Negroni.png"
cp "$SOURCE/Non V thali.png" "$TARGET/non-v-thali.png" 2>/dev/null && echo "✅ non-v-thali.png" || echo "⚠️  Missing: Non V thali.png"
cp "$SOURCE/non v platter.png" "$TARGET/non-v-platter.png" 2>/dev/null && echo "✅ non-v-platter.png" || echo "⚠️  Missing: non v platter.png"
cp "$SOURCE/Palak paneer.png" "$TARGET/palak-paneer.png" 2>/dev/null && echo "✅ palak-paneer.png" || echo "⚠️  Missing: Palak paneer.png"
cp "$SOURCE/Paneer Pasanda.png" "$TARGET/paneer-pasanda.png" 2>/dev/null && echo "✅ paneer-pasanda.png" || echo "⚠️  Missing: Paneer Pasanda.png"
cp "$SOURCE/Pineapple paneer tikka.png" "$TARGET/pineapple-paneer-tikka.png" 2>/dev/null && echo "✅ pineapple-paneer-tikka.png" || echo "⚠️  Missing: Pineapple paneer tikka.png"
cp "$SOURCE/Roosted Pappad.png" "$TARGET/roasted-papad.png" 2>/dev/null && echo "✅ roasted-papad.png" || echo "⚠️  Missing: Roosted Pappad.png"
cp "$SOURCE/Samosas Full.png" "$TARGET/samosas-full.png" 2>/dev/null && echo "✅ samosas-full.png" || echo "⚠️  Missing: Samosas Full.png"
cp "$SOURCE/V dum biryani.png" "$TARGET/vegetable-biryani.png" 2>/dev/null && echo "✅ vegetable-biryani.png" || echo "⚠️  Missing: V dum biryani.png"
cp "$SOURCE/Virgin mojito.png" "$TARGET/virgin-mojito.png" 2>/dev/null && echo "✅ virgin-mojito.png" || echo "⚠️  Missing: Virgin mojito.png"
cp "$SOURCE/Virgin sour.png" "$TARGET/virgin-sour.png" 2>/dev/null && echo "✅ virgin-sour.png" || echo "⚠️  Missing: Virgin sour.png"

echo ""
echo "=== Copy Complete ==="
copied=$(find "$TARGET" -name "*.png" -type f -newer "$TARGET/IMAGES_NEEDED.txt" 2>/dev/null | wc -l | tr -d ' ')
echo "Copied $copied new images"
